package:
  name: pylation
  version: "0.1a"

source:
  git_rev: v0.1a
  git_url: https://github.com/bheff88/pylation.git

requirements:
  build:
    - python
    - setuptools
  run:
    - python

about:
  home: https://github.com/bheff88/pylation
  license: MIT
  license_file: LICENSE
